---
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pipebin
      POSTGRES_PASSWORD: pipebin
      POSTGRES_DB: pipebin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
